# Generated by Django 4.1 on 2022-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_alter_question_options_alter_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/profile_picture/img.png', upload_to='media/profile_picture'),
        ),
    ]
