# Generated by Django 4.1 on 2022-09-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_profile_alter_post_author_alter_thread_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
