# Generated by Django 4.1 on 2022-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_alter_user_email_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
