# Generated by Django 4.1 on 2022-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='name_and_surname',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
    ]
