# Generated by Django 4.1 on 2022-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_remove_profile_name_remove_profile_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name_and_surname',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
