# Generated by Django 4.1 on 2022-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_alter_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_useful',
            field=models.BooleanField(null=True, verbose_name='Is Useful'),
        ),
    ]
