# Generated by Django 4.1 on 2022-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_answer_commenttoanswer_question_remove_thread_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttoanswer',
            name='comment_to_answer',
        ),
        migrations.AddField(
            model_name='commenttoanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='backends.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backends.question'),
        ),
    ]
