# Generated by Django 4.1 on 2022-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0011_remove_question_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defolt_user1.png', upload_to='profile_picture'),
        ),
    ]
