# Generated by Django 4.1 on 2022-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
